openapi: 3.0.1
info:
  title: AirInterface_2.0.0-tsi.240102.1740+simulator.1
  version: 2.0.0

paths:

########################################################################################################################
#   Generic Paths
########################################################################################################################
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-capability:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedAirInterfaceCapability
      summary: 'Provides AirInterfaceCapability from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'AirInterfaceCapability provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - air-interface-2-0:air-interface-capability
                properties:
                  air-interface-2-0:air-interface-capability:
                    $ref: '#/components/schemas/air-interface-capability'
                example:
                  air-interface-2-0:air-interface-capability:
                    type-of-equipment: 'string'
                    tx-frequency-min: 0
                    tx-frequency-max: 0
                    rx-frequency-min: 0
                    rx-frequency-max: 0
                    duplex-distance-is-freely-configurable: true
                    duplex-distance-list:
                      - 0
                    transmission-mode-list:
                      - transmission-mode-name: 'string'
                        transmission-mode-rank: 0
                        channel-bandwidth: 0
                        modulation-scheme: 0
                        code-rate: 0
                        symbol-rate-reduction-factor: 0
                        tx-power-min: 0
                        tx-power-max: 0
                        rx-threshold: 0
                        am-upshift-level: 0
                        am-downshift-level: 0
                        xpic-is-avail: true
                        supported-as-fixed-configuration: true
                        modulation-scheme-name-at-lct: 'string'
                    auto-freq-select-is-avail: true
                    receiver-on-off-is-avail: true
                    adaptive-modulation-is-avail: true
                    atpc-is-avail: true
                    atpc-range: 0
                    supported-radio-signal-id-datatype: 'air-interface-2-0:RADIO_SIGNAL_ID_DATATYPE_TYPE_INTEGER'
                    supported-radio-signal-id-length: 0
                    expected-equals-transmitted-radio-signal-id: true
                    encryption-is-avail: true
                    supported-loop-back-kind-list:
                      - 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_REMOTE'
                    maintenance-timer-range: 'string'
                    acm-threshold-cross-alarms-is-avail: true
                    clearing-threshold-cross-alarms-is-avail: true
                    performance-monitoring-is-avail: true
                    direction-of-acm-performance-values: 'air-interface-2-0:DIRECTION_TYPE_TX'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-configuration:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedAirInterfaceConfiguration
      summary: 'Provides AirInterfaceConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'AirInterfaceConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - air-interface-2-0:air-interface-configuration
                properties:
                  air-interface-2-0:air-interface-configuration:
                    $ref: '#/components/schemas/air-interface-configuration'
                example:
                  air-interface-2-0:air-interface-configuration:
                    air-interface-name: 'string'
                    remote-air-interface-name: 'string'
                    transmitted-radio-signal-id:
                      numeric-radio-signal-id: 0
                      alphanumeric-radio-signal-id: 'string'
                    expected-radio-signal-id:
                      numeric-radio-signal-id: 0
                      alphanumeric-radio-signal-id: 'string'
                    tx-frequency: 0
                    rx-frequency: 0
                    duplex-distance: 0
                    transmission-mode-min: 'string'
                    transmission-mode-max: 'string'
                    power-is-on: true
                    transmitter-is-on: true
                    receiver-is-on: true
                    tx-power: 0
                    adaptive-modulation-is-on: true
                    xpic-is-on: true
                    mimo-is-on: true
                    alic-is-on: true
                    atpc-is-on: true
                    atpc-thresh-upper: 0
                    atpc-thresh-lower: 0
                    atpc-tx-power-min: 0
                    auto-freq-select-is-on: true
                    auto-freq-select-range: 0
                    modulation-is-on: true
                    encryption-is-on: true
                    cryptographic-key: 'string'
                    loop-back-kind-on: 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_REMOTE'
                    maintenance-timer: 0
                    g-826-threshold-cross-alarm-list:
                      - g-826-value-kind: 'air-interface-2-0:G_826_TYPE_ES'
                        alarm-raising-threshold: 0
                        alarm-clearing-threshold: 0
                        granularity-period: 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                    xlts-threshold-cross-alarm-list:
                      - level-threshold-second-kind: 'air-interface-2-0:XLEVEL_THRESHOLD_SECOND_KIND_TYPE_RLTS'
                        xlts-level: 0
                        amount-of-seconds: 0
                        granularity-period: 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                        xlts-threshold-cross-alarm-definition-number: 0
                    acm-threshold-cross-alarm-list:
                      - acm-threshold-cross-alarm-definition-number: 0
                        transmission-mode: 'string'
                        seconds-for-raising-alarm: 0
                        seconds-for-clearing-alarm: 0
                        granularity-period: 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                    performance-monitoring-is-on: true
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-status:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedAirInterfaceStatus
      summary: 'Provides AirInterfaceStatus from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'AirInterfaceStatus provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - air-interface-2-0:air-interface-status
                properties:
                  air-interface-2-0:air-interface-status:
                    $ref: '#/components/schemas/air-interface-status'
                example:
                  air-interface-2-0:air-interface-status:
                    interface-status: 'air-interface-2-0:INTERFACE_STATUS_TYPE_UP'
                    tx-frequency-cur: 0
                    rx-frequency-cur: 0
                    transmission-mode-cur: 'string'
                    received-radio-signal-id:
                      numeric-radio-signal-id: 0
                      alphanumeric-radio-signal-id: 'string'
                    link-is-up: true
                    xpic-is-up: true
                    mimo-is-up: true
                    alic-is-up: true
                    atpc-is-up: true
                    auto-freq-select-is-up: true
                    local-end-point-id: 'string'
                    remote-end-point-id: 'string'
                    loop-back-kind-up: 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_REMOTE'
                    performance-monitoring-is-up: true
                    rx-level-cur: 0
                    tx-level-cur: 0
                    snir-cur: 0
                    xpd-cur: 0
                    rf-temp-cur: 0
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-current-performance:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedAirInterfaceCurrentPerformance
      summary: 'Provides AirInterfaceCurrentPerformance from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'AirInterfaceCurrentPerformance provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - air-interface-2-0:air-interface-current-performance
                properties:
                  air-interface-2-0:air-interface-current-performance:
                    $ref: '#/components/schemas/air-interface-current-performance'
                example:
                  air-interface-2-0:air-interface-current-performance:
                    number-of-current-performance-sets: 0
                    current-performance-data-list:
                      - timestamp: '2010-11-20T14:00:00+01:00'
                        suspect-interval-flag: true
                        elapsed-time: 'string'
                        scanner-id: 'string'
                        granularity-period: 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                        performance-data:
                          es: 0
                          ses: 0
                          cses: 0
                          unavailability: 0
                          tx-level-min: 0
                          tx-level-max: 0
                          tx-level-avg: 0
                          rx-level-min: 0
                          rx-level-max: 0
                          rx-level-avg: 0
                          time-xstates-list:
                            - time-xstate-sequence-number: 0
                              transmission-mode: 'string'
                              time: 0
                          snir-min: 0
                          snir-max: 0
                          snir-avg: 0
                          xpd-min: 0
                          xpd-max: 0
                          xpd-avg: 0
                          rf-temp-min: 0
                          rf-temp-max: 0
                          rf-temp-avg: 0
                          defect-blocks-sum: 0
                          time-period: 0
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-historical-performances:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedAirInterfaceHistoricalPerformances
      summary: 'Provides AirInterfaceHistoricalPerformances from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'AirInterfaceHistoricalPerformances provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - air-interface-2-0:air-interface-historical-performances
                properties:
                  air-interface-2-0:air-interface-historical-performances:
                    $ref: '#/components/schemas/air-interface-historical-performances'
                example:
                  air-interface-2-0:air-interface-historical-performances:
                    number-of-historical-performance-sets: 0
                    time-of-latest-change: '3458-90-13T36:05:34-24:27'
                    historical-performance-data-list:
                      - suspect-interval-flag: true
                        history-data-id: 'string'
                        granularity-period: 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                        period-end-time: '2010-11-20T14:00:00+01:00'
                        performance-data:
                          es: 0
                          ses: 0
                          cses: 0
                          unavailability: 0
                          tx-level-min: 0
                          tx-level-max: 0
                          tx-level-avg: 0
                          rx-level-min: 0
                          rx-level-max: 0
                          rx-level-avg: 0
                          time-xstates-list:
                            - time-xstate-sequence-number: 0
                              transmission-mode: 'string'
                              time: 0
                          snir-min: 0
                          snir-max: 0
                          snir-avg: 0
                          xpd-min: 0
                          xpd-max: 0
                          xpd-avg: 0
                          rf-temp-min: 0
                          rf-temp-max: 0
                          rf-temp-avg: 0
                          defect-blocks-sum: 0
                          time-period: 0
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'

  /core-model-1-4:network-control-domain=live/control-construct={mountName}/air-interface-2-0:clear-threshold-cross-alarms:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postClearThresholdCrossAlarms
      summary: 'Clears all currently active threshold cross alarms at the referenced AirInterface'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - affected-air-interface
                  properties:
                    affected-air-interface:
                      type: string
      responses:
        '204':
          description: 'Threshold cross alarms cleared'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        description: 'Empty string accepted from external applications.'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        description: 'Empty string accepted from external applications.'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
    mountName:
      name: mountName
      in: path
      required: true
      schema:
        type: string
        example: '222250001'
      description: 'The mountName of the device that is addressed by the request'
    uuid:
      name: uuid
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within the device'
    uuid1:
      name: uuid1
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Another instance identifier that is unique within the device'
    localId:
      name: localId
      in: path
      required: true
      schema:
        type: string
        example: 'LP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within its list'
    fields:
      name: fields
      in: query
      required: false
      schema:
        type: string
        example: 'node(node-id;netconf-node-topology:connection-status)'
      description: 'Query parameter to filter ressources according to RFC8040 fields filter spec'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
        backend-time:
          schema:
            type: integer
            example: 850
          description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
  headers:
    x-correlator:
      schema:
        type: string
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
    exec-time:
      schema:
        type: integer
        example: 1100
      description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
    backend-time:
      schema:
        type: integer
        example: 850
      description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    life-cycle-state:
      schema:
        type: string
        enum:
          - 'EXPERIMENTAL'
          - 'OPERATIONAL'
          - 'DEPRECATED'
          - 'OBSOLETE'
          - 'UNKNOWN'
          - 'NOT_YET_DEFINED'
        example: 'EXPERIMENTAL'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    air-interface-capability:
      type: object
      required:
        - type-of-equipment
        - tx-frequency-min
        - tx-frequency-max
        - rx-frequency-min
        - rx-frequency-max
        - duplex-distance-is-freely-configurable
        - transmission-mode-list
        - auto-freq-select-is-avail
        - receiver-on-off-is-avail
        - adaptive-modulation-is-avail
        - atpc-is-avail
        - atpc-range
        - supported-radio-signal-id-datatype
        - supported-radio-signal-id-length
        - expected-equals-transmitted-radio-signal-id
        - encryption-is-avail
        - supported-loop-back-kind-list
        - maintenance-timer-range
        - acm-threshold-cross-alarms-is-avail
        - clearing-threshold-cross-alarms-is-avail
        - performance-monitoring-is-avail
        - direction-of-acm-performance-values
      properties:
        type-of-equipment:
          type: string
        tx-frequency-min:
          type: integer
          format: int32
        tx-frequency-max:
          type: integer
          format: int32
        rx-frequency-min:
          type: integer
          format: int32
        rx-frequency-max:
          type: integer
          format: int32
        duplex-distance-is-freely-configurable:
          type: boolean
        duplex-distance-list:
          type: array
          items:
            type: integer
            format: int32
        transmission-mode-list:
          type: array
          x-key: transmission-mode-name
          items:
            type: object
            required:
              - transmission-mode-name
              - transmission-mode-rank
              - channel-bandwidth
              - modulation-scheme
              - code-rate
              - symbol-rate-reduction-factor
              - tx-power-min
              - tx-power-max
              - rx-threshold
              - am-upshift-level
              - am-downshift-level
              - xpic-is-avail
              - supported-as-fixed-configuration
              - modulation-scheme-name-at-lct
            properties:
              transmission-mode-name:
                type: string
              transmission-mode-rank:
                type: integer
                format: int32
              channel-bandwidth:
                type: integer
                format: int32
              modulation-scheme:
                type: integer
                format: int16
              code-rate:
                type: integer
                format: int8
              symbol-rate-reduction-factor:
                type: integer
                format: int8
              tx-power-min:
                type: integer
                format: int8
              tx-power-max:
                type: integer
                format: int8
              rx-threshold:
                type: integer
                format: int16
              am-upshift-level:
                type: integer
                format: int8
              am-downshift-level:
                type: integer
                format: int8
              xpic-is-avail:
                type: boolean
              supported-as-fixed-configuration:
                type: boolean
              modulation-scheme-name-at-lct:
                type: string
        auto-freq-select-is-avail:
          type: boolean
        receiver-on-off-is-avail:
          type: boolean
        adaptive-modulation-is-avail:
          type: boolean
        atpc-is-avail:
          type: boolean
        atpc-range:
          type: integer
          format: int8
        supported-radio-signal-id-datatype:
          type: string
          enum:
            - 'air-interface-2-0:RADIO_SIGNAL_ID_DATATYPE_TYPE_INTEGER'
            - 'air-interface-2-0:RADIO_SIGNAL_ID_DATATYPE_TYPE_STRING'
            - 'air-interface-2-0:RADIO_SIGNAL_ID_DATATYPE_TYPE_NOT_YET_DEFINED'
        supported-radio-signal-id-length:
          type: integer
          format: int16
        expected-equals-transmitted-radio-signal-id:
          type: boolean
        encryption-is-avail:
          type: boolean
        supported-loop-back-kind-list:
          type: array
          minItems: 1
          maxItems: 4
          items:
            type: string
            enum:
              - 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_REMOTE'
              - 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_LOCAL'
              - 'air-interface-2-0:LOOP_BACK_TYPE_IF_TO_REMOTE'
              - 'air-interface-2-0:LOOP_BACK_TYPE_IF_TO_LOCAL'
              - 'air-interface-2-0:LOOP_BACK_TYPE_NONE'
        maintenance-timer-range:
          type: string
        acm-threshold-cross-alarms-is-avail:
          type: boolean
        clearing-threshold-cross-alarms-is-avail:
          type: boolean
        performance-monitoring-is-avail:
          type: boolean
        direction-of-acm-performance-values:
          type: string
          enum:
            - 'air-interface-2-0:DIRECTION_TYPE_TX'
            - 'air-interface-2-0:DIRECTION_TYPE_RX'
            - 'air-interface-2-0:DIRECTION_TYPE_NONE'
    air-interface-configuration:
      type: object
      required:
        - air-interface-name
        - remote-air-interface-name
        - transmitted-radio-signal-id
        - expected-radio-signal-id
        - tx-frequency
        - rx-frequency
        - duplex-distance
        - transmission-mode-min
        - transmission-mode-max
        - power-is-on
        - transmitter-is-on
        - receiver-is-on
        - tx-power
        - adaptive-modulation-is-on
        - xpic-is-on
        - mimo-is-on
        - alic-is-on
        - atpc-is-on
        - atpc-thresh-upper
        - atpc-thresh-lower
        - atpc-tx-power-min
        - auto-freq-select-is-on
        - auto-freq-select-range
        - modulation-is-on
        - encryption-is-on
        - cryptographic-key
        - loop-back-kind-on
        - maintenance-timer
        - performance-monitoring-is-on
      properties:
        air-interface-name:
          type: string
        remote-air-interface-name:
          type: string
        transmitted-radio-signal-id:
          type: object
          required:
            - numeric-radio-signal-id
            - alphanumeric-radio-signal-id
          properties:
            numeric-radio-signal-id:
              type: integer
              format: int32
            alphanumeric-radio-signal-id:
              type: string
        expected-radio-signal-id:
          type: object
          required:
            - numeric-radio-signal-id
            - alphanumeric-radio-signal-id
          properties:
            numeric-radio-signal-id:
              type: integer
              format: int32
            alphanumeric-radio-signal-id:
              type: string
        tx-frequency:
          type: integer
          format: int32
        rx-frequency:
          type: integer
          format: int32
        duplex-distance:
          type: integer
          format: int32
        transmission-mode-min:
          type: string
        transmission-mode-max:
          type: string
        power-is-on:
          type: boolean
        transmitter-is-on:
          type: boolean
        receiver-is-on:
          type: boolean
        tx-power:
          type: integer
          format: int8
        adaptive-modulation-is-on:
          type: boolean
        xpic-is-on:
          type: boolean
        mimo-is-on:
          type: boolean
        alic-is-on:
          type: boolean
        atpc-is-on:
          type: boolean
        atpc-thresh-upper:
          type: integer
          format: int16
        atpc-thresh-lower:
          type: integer
          format: int16
        atpc-tx-power-min:
          type: integer
          format: int8
        auto-freq-select-is-on:
          type: boolean
        auto-freq-select-range:
          type: integer
          format: int8
        modulation-is-on:
          type: boolean
        encryption-is-on:
          type: boolean
        cryptographic-key:
          type: string
        loop-back-kind-on:
          type: string
          enum:
            - 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_REMOTE'
            - 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_LOCAL'
            - 'air-interface-2-0:LOOP_BACK_TYPE_IF_TO_REMOTE'
            - 'air-interface-2-0:LOOP_BACK_TYPE_IF_TO_LOCAL'
            - 'air-interface-2-0:LOOP_BACK_TYPE_NONE'
        maintenance-timer:
          type: integer
          format: int32
        g-826-threshold-cross-alarm-list:
          type: array
          x-key: g-826-value-kind granularity-period
          items:
            type: object
            required:
              - g-826-value-kind
              - alarm-raising-threshold
              - alarm-clearing-threshold
              - granularity-period
            properties:
              g-826-value-kind:
                type: string
                enum:
                  - 'air-interface-2-0:G_826_TYPE_ES'
                  - 'air-interface-2-0:G_826_TYPE_SES'
                  - 'air-interface-2-0:G_826_TYPE_CSES'
                  - 'air-interface-2-0:G_826_TYPE_UAS'
                  - 'air-interface-2-0:G_826_TYPE_NOT_SPECIFIED'
              alarm-raising-threshold:
                type: integer
                format: int32
              alarm-clearing-threshold:
                type: integer
                format: int32
              granularity-period:
                type: string
                enum:
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_NOT_YET_DEFINED'
        xlts-threshold-cross-alarm-list:
          type: array
          x-key: level-threshold-second-kind granularity-period xlts-threshold-cross-alarm-definition-number
          items:
            type: object
            required:
              - level-threshold-second-kind
              - xlts-level
              - amount-of-seconds
              - granularity-period
              - xlts-threshold-cross-alarm-definition-number
            properties:
              level-threshold-second-kind:
                type: string
                enum:
                  - 'air-interface-2-0:XLEVEL_THRESHOLD_SECOND_KIND_TYPE_RLTS'
                  - 'air-interface-2-0:XLEVEL_THRESHOLD_SECOND_KIND_TYPE_TLTS'
                  - 'air-interface-2-0:XLEVEL_THRESHOLD_SECOND_KIND_TYPE_NOT_YET_DEFINED'
              xlts-level:
                type: integer
                format: int8
              amount-of-seconds:
                type: integer
                format: int32
              granularity-period:
                type: string
                enum:
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_NOT_YET_DEFINED'
              xlts-threshold-cross-alarm-definition-number:
                type: integer
                format: int8
        acm-threshold-cross-alarm-list:
          type: array
          x-key: acm-threshold-cross-alarm-definition-number granularity-period
          items:
            type: object
            required:
              - acm-threshold-cross-alarm-definition-number
              - transmission-mode
              - seconds-for-raising-alarm
              - seconds-for-clearing-alarm
              - granularity-period
            properties:
              acm-threshold-cross-alarm-definition-number:
                type: integer
                format: int8
              transmission-mode:
                type: string
              seconds-for-raising-alarm:
                type: integer
                format: int32
              seconds-for-clearing-alarm:
                type: integer
                format: int32
              granularity-period:
                type: string
                enum:
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_NOT_YET_DEFINED'
        performance-monitoring-is-on:
          type: boolean
    air-interface-status:
      type: object
      required:
        - interface-status
        - tx-frequency-cur
        - rx-frequency-cur
        - transmission-mode-cur
        - received-radio-signal-id
        - link-is-up
        - xpic-is-up
        - mimo-is-up
        - alic-is-up
        - atpc-is-up
        - auto-freq-select-is-up
        - local-end-point-id
        - remote-end-point-id
        - loop-back-kind-up
        - performance-monitoring-is-up
        - rx-level-cur
        - tx-level-cur
        - snir-cur
        - xpd-cur
        - rf-temp-cur
      properties:
        interface-status:
          type: string
          enum:
            - 'air-interface-2-0:INTERFACE_STATUS_TYPE_UP'
            - 'air-interface-2-0:INTERFACE_STATUS_TYPE_DOWN'
            - 'air-interface-2-0:INTERFACE_STATUS_TYPE_TESTING'
            - 'air-interface-2-0:INTERFACE_STATUS_TYPE_UNKNOWN'
            - 'air-interface-2-0:INTERFACE_STATUS_TYPE_DORMANT'
            - 'air-interface-2-0:INTERFACE_STATUS_TYPE_NOT_PRESENT'
            - 'air-interface-2-0:INTERFACE_STATUS_TYPE_NOT_YET_DEFINED'
        tx-frequency-cur:
          type: integer
          format: int32
        rx-frequency-cur:
          type: integer
          format: int32
        transmission-mode-cur:
          type: string
        received-radio-signal-id:
          type: object
          required:
            - numeric-radio-signal-id
            - alphanumeric-radio-signal-id
          properties:
            numeric-radio-signal-id:
              type: integer
              format: int32
            alphanumeric-radio-signal-id:
              type: string
        link-is-up:
          type: boolean
        xpic-is-up:
          type: boolean
        mimo-is-up:
          type: boolean
        alic-is-up:
          type: boolean
        atpc-is-up:
          type: boolean
        auto-freq-select-is-up:
          type: boolean
        local-end-point-id:
          type: string
        remote-end-point-id:
          type: string
        loop-back-kind-up:
          type: string
          enum:
            - 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_REMOTE'
            - 'air-interface-2-0:LOOP_BACK_TYPE_RF_TO_LOCAL'
            - 'air-interface-2-0:LOOP_BACK_TYPE_IF_TO_REMOTE'
            - 'air-interface-2-0:LOOP_BACK_TYPE_IF_TO_LOCAL'
            - 'air-interface-2-0:LOOP_BACK_TYPE_NONE'
        performance-monitoring-is-up:
          type: boolean
        rx-level-cur:
          type: integer
          format: int8
        tx-level-cur:
          type: integer
          format: int8
        snir-cur:
          type: integer
          format: int8
        xpd-cur:
          type: integer
          format: int8
        rf-temp-cur:
          type: integer
          format: int8
    air-interface-current-performance:
      type: object
      required:
        - number-of-current-performance-sets
        - current-performance-data-list
      properties:
        number-of-current-performance-sets:
          type: integer
          format: int8
        current-performance-data-list:
          type: array
          minItems: 1
          maxItems: 2
          items:
            type: object
            required:
              - timestamp
              - suspect-interval-flag
              - elapsed-time
              - scanner-id
              - granularity-period
              - performance-data
            properties:
              timestamp:
                type: string
                pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
              suspect-interval-flag:
                type: boolean
              elapsed-time:
                type: string
              scanner-id:
                type: string
              granularity-period:
                type: string
                enum:
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_NOT_YET_DEFINED'
              performance-data:
                type: object
                required:
                  - es
                  - ses
                  - cses
                  - unavailability
                  - tx-level-min
                  - tx-level-max
                  - tx-level-avg
                  - rx-level-min
                  - rx-level-max
                  - rx-level-avg
                  - time-xstates-list
                  - snir-min
                  - snir-max
                  - snir-avg
                  - xpd-min
                  - xpd-max
                  - xpd-avg
                  - rf-temp-min
                  - rf-temp-max
                  - rf-temp-avg
                  - defect-blocks-sum
                  - time-period
                properties:
                  es:
                    type: integer
                    format: int32
                  ses:
                    type: integer
                    format: int32
                  cses:
                    type: integer
                    format: int32
                  unavailability:
                    type: integer
                    format: int32
                  tx-level-min:
                    type: integer
                    format: int8
                  tx-level-max:
                    type: integer
                    format: int8
                  tx-level-avg:
                    type: integer
                    format: int8
                  rx-level-min:
                    type: integer
                    format: int8
                  rx-level-max:
                    type: integer
                    format: int8
                  rx-level-avg:
                    type: integer
                    format: int8
                  time-xstates-list:
                    type: array
                    minItems: 1
                    x-key: time-xstate-sequence-number
                    items:
                      type: object
                      required:
                        - time-xstate-sequence-number
                        - transmission-mode
                        - time
                      properties:
                        time-xstate-sequence-number:
                          type: integer
                          format: int8
                        transmission-mode:
                          type: string
                        time:
                          type: integer
                          format: int32
                  snir-min:
                    type: integer
                    format: int8
                  snir-max:
                    type: integer
                    format: int8
                  snir-avg:
                    type: integer
                    format: int8
                  xpd-min:
                    type: integer
                    format: int8
                  xpd-max:
                    type: integer
                    format: int8
                  xpd-avg:
                    type: integer
                    format: int8
                  rf-temp-min:
                    type: integer
                    format: int8
                  rf-temp-max:
                    type: integer
                    format: int8
                  rf-temp-avg:
                    type: integer
                    format: int8
                  defect-blocks-sum:
                    type: integer
                    format: int16
                  time-period:
                    type: integer
                    format: int32
    air-interface-historical-performances:
      type: object
      required:
        - number-of-historical-performance-sets
        - time-of-latest-change
      properties:
        number-of-historical-performance-sets:
          type: integer
          format: int16
        time-of-latest-change:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
        historical-performance-data-list:
          type: array
          x-key: granularity-period period-end-time
          items:
            type: object
            required:
              - suspect-interval-flag
              - history-data-id
              - granularity-period
              - period-end-time
              - performance-data
            properties:
              suspect-interval-flag:
                type: boolean
              history-data-id:
                type: string
              granularity-period:
                type: string
                enum:
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_UNKNOWN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS'
                  - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_NOT_YET_DEFINED'
              period-end-time:
                type: string
                pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
              performance-data:
                type: object
                required:
                  - es
                  - ses
                  - cses
                  - unavailability
                  - tx-level-min
                  - tx-level-max
                  - tx-level-avg
                  - rx-level-min
                  - rx-level-max
                  - rx-level-avg
                  - time-xstates-list
                  - snir-min
                  - snir-max
                  - snir-avg
                  - xpd-min
                  - xpd-max
                  - xpd-avg
                  - rf-temp-min
                  - rf-temp-max
                  - rf-temp-avg
                  - defect-blocks-sum
                  - time-period
                properties:
                  es:
                    type: integer
                    format: int32
                  ses:
                    type: integer
                    format: int32
                  cses:
                    type: integer
                    format: int32
                  unavailability:
                    type: integer
                    format: int32
                  tx-level-min:
                    type: integer
                    format: int8
                  tx-level-max:
                    type: integer
                    format: int8
                  tx-level-avg:
                    type: integer
                    format: int8
                  rx-level-min:
                    type: integer
                    format: int8
                  rx-level-max:
                    type: integer
                    format: int8
                  rx-level-avg:
                    type: integer
                    format: int8
                  time-xstates-list:
                    type: array
                    x-key: time-xstate-sequence-number
                    items:
                      type: object
                      required:
                        - time-xstate-sequence-number
                        - transmission-mode
                        - time
                      properties:
                        time-xstate-sequence-number:
                          type: integer
                          format: int8
                        transmission-mode:
                          type: string
                        time:
                          type: integer
                          format: int32
                  snir-min:
                    type: integer
                    format: int8
                  snir-max:
                    type: integer
                    format: int8
                  snir-avg:
                    type: integer
                    format: int8
                  xpd-min:
                    type: integer
                    format: int8
                  xpd-max:
                    type: integer
                    format: int8
                  xpd-avg:
                    type: integer
                    format: int8
                  rf-temp-min:
                    type: integer
                    format: int8
                  rf-temp-max:
                    type: integer
                    format: int8
                  rf-temp-avg:
                    type: integer
                    format: int8
                  defect-blocks-sum:
                    type: integer
                    format: int16
                  time-period:
                    type: integer
                    format: int32
    air-interface-2-0:clear-threshold-cross-alarms:

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic
